# application-dev.yml
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/knowledge_base_dev
    username: kb_user
    driver-class-name: org.postgresql.Driver
    password: kb_password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms

elasticsearch:
  host: localhost
  port: 9200
  username:
  password:

logging:
  level:
    com.knowledgebase: DEBUG
    org.springframework.web: DEBUG