server:
  port: 8080
  # Comment out the context-path to test if that's causing issues
  # servlet:
  #   context-path: /api

spring:
  application:
    name: knowledge-base-backend
  elasticsearch:
    uris: http://${elasticsearch.host}:${elasticsearch.port}
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      continue-on-error: true

  main:
    allow-bean-definition-overriding: true

  security:
    filter:
      order: 5

# Elasticsearch configuration
elasticsearch:
  enabled: true
  host: ${ELASTICSEARCH_HOST:localhost}
  port: ${ELASTICSEARCH_PORT:9200}
  username: ${ELASTICSEARCH_USERNAME:}
  password: ${ELASTICSEARCH_PASSWORD:}
  


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

app:
  file:
    upload-dir: ./uploads
  elasticsearch:
    index:
      name: documents
  chinese:
    dictionary:
      path: classpath:static/chinese-synonyms.txt

logging:
  level:
    com.knowledgebase: DEBUG
    org.elasticsearch: INFO
    org.springframework.data.elasticsearch: DEBUG
    org.springframework.security: DEBUG
    org.yiqixue.kbbackend: DEBUG
