server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: knowledge-base-backend

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    elasticsearch:
      repositories:
        enabled: true

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

app:
  file:
    upload-dir: ./uploads
  elasticsearch:
    index:
      name: documents
  chinese:
    dictionary:
      path: classpath:static/chinese-synonyms.txt

logging:
  level:
    com.knowledgebase: DEBUG
    org.elasticsearch: INFO
    org.springframework.data.elasticsearch: DEBUG
